- name: Work on OOB-Server
  hosts: oob-server
  become: yes
  vars:
    desired_netq_release: "1.1.0"
    desired_ansible_version: "2.4.1.0"
    bootcamp_automation_branch: "v3.4.2_automationupdate"
  gather_facts: no
  roles:
  - prepare-oob-server

- name: Work on the Switches
  hosts: spine*:leaf*
  become: yes
  vars:
   desired_cl_release: "3.4.2"
  gather_facts: no
  roles:
  - prepare-switches

- name: Work on the Servers
  hosts: server*
  become: yes
  vars:
   desired_ubuntu_release: "16.04"
  gather_facts: no
  roles:
  - prepare-servers
